# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('submission_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=200, null=True)),
                ('family', models.CharField(max_length=200, null=True)),
                ('subfamily', models.CharField(max_length=200, null=True)),
                ('genus', models.CharField(max_length=200, null=True)),
                ('species', models.CharField(max_length=200, null=True)),
                ('genome', models.CharField(max_length=200, null=True)),
                ('history', models.CharField(max_length=200, null=True)),
                ('host', models.CharField(choices=[('V', 'Vertebrate'), ('P', 'Plant or Fungi'), ('I', 'Invertebrate'), ('B', 'Bacteria')], max_length=1, null=True)),
                ('sequence', models.ManyToManyField(blank=True, to='viruses.Sequence')),
            ],
        ),
    ]
