# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viruses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virus',
            name='history',
        ),
        migrations.RemoveField(
            model_name='virus',
            name='sequence',
        ),
        migrations.AddField(
            model_name='sequence',
            name='sequence_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequence',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viruses.Virus'),
        ),
        migrations.AlterField(
            model_name='virus',
            name='family',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='virus',
            name='genome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='virus',
            name='genus',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='virus',
            name='host',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='virus',
            name='order',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='virus',
            name='species',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='virus',
            name='subfamily',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
