# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viruses', '0003_auto_20180720_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='name',
            new_name='nucleotides',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequence_name',
            new_name='species',
        ),
    ]
